### PR TITLE
On-screen clipboard

### PR DESCRIPTION
**Pull request by m1k1o**
In case clipboard sync is not working, because user is not using HTTP there is on-screen clipboard. It's just textarea synchronized with neko's clipboard.

image

One something is copied inside neko, it appears there, Also vice-versa.
image

Maybe, It sould be visible **only** if there is regular clipboard **not available**. Or always?

### CODE REVIEW

**Comment by alectrocute** [comment]
I personally think it makes more sense if it's only if the regular clipboard is not available. Typically, this feature is left best mostly transparent – albeit this feature is a very elegant fallback for some clients/networks.

**Comment by m1k1o** [comment]
Now is it only visible, when regular clipboard is not available.

**Comment by GigaFyde** [comment]
Make this a toggle please, since the regular clipboard sync might not always be reliable

**Comment by nurdism** [comment]
I like this feature, but I agree there should be a toggle in maybe the setting panel

**Comment by alectrocute** [comment]
@m1k1o Where you at on this? I can finish it off if you need.

**Comment by m1k1o** [comment]
@alectrocute that clipboard feature is finished and working. it shows only when user is having neko via HTTP, since only HTTPS supports clipboard. but it should be as toggle in settings, because e.g. Firefox is not supporting clipboard at all and for some users is not clipboard working reliably.

basically just that settings toggle is missing. and that value should then be accessed via this getter to hide and show clipboard https://github.com/nurdism/neko/pull/95/commits/4c0bde0811a012537a67b07e83557bdc918841c0#diff-3049ea6532dd249a5d96fffd756bb08e91da932a04c2c19970102b5e0beaf806R240-R243.

**Pull request closed without merging**
